name: AllInOne
version: 1.0.0
main: RTG\AllInOne\Loader
api:
    - 2.1.0
    - 3.0.0-ALPHA4
    - 3.0.0-ALPHA5
commands:
    freeze:
        permission: allinone.command.freeze
    rule:
        permission: allinone.command.rule